-- ClaimBot PostgreSQL baseline migration.
-- SQLAlchemy can create the same schema for local SQLite development; use this file for an explicit production baseline.
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY, email VARCHAR(320) UNIQUE NOT NULL, password_hash TEXT NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'coordinator', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS insurers (id BIGSERIAL PRIMARY KEY, slug VARCHAR(120) UNIQUE NOT NULL, name VARCHAR(255) NOT NULL, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS tpas (id BIGSERIAL PRIMARY KEY, slug VARCHAR(120) UNIQUE NOT NULL, name VARCHAR(255) NOT NULL, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS plans (id BIGSERIAL PRIMARY KEY, insurer_id BIGINT REFERENCES insurers(id), tpa_id BIGINT REFERENCES tpas(id), name VARCHAR(255) NOT NULL, version VARCHAR(120) NOT NULL DEFAULT 'unknown', effective_from VARCHAR(32), effective_to VARCHAR(32), is_current BOOLEAN NOT NULL DEFAULT TRUE, metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS policies (id BIGSERIAL PRIMARY KEY, plan_id BIGINT REFERENCES plans(id), policy_ref VARCHAR(255) NOT NULL, source_mode VARCHAR(40) NOT NULL DEFAULT 'user_supplied', raw_text TEXT, structured_json JSONB NOT NULL DEFAULT '{}'::jsonb, version VARCHAR(120) NOT NULL DEFAULT 'unknown', is_current BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS benefits (id BIGSERIAL PRIMARY KEY, policy_id BIGINT NOT NULL REFERENCES policies(id), category VARCHAR(80) NOT NULL, status VARCHAR(40) NOT NULL, annual_limit BIGINT, remaining_limit BIGINT, session_limit BIGINT, preauthorization_required BOOLEAN, nssf_coordination VARCHAR(40) NOT NULL DEFAULT 'unknown', metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS source_documents (id BIGSERIAL PRIMARY KEY, source_key VARCHAR(160) UNIQUE NOT NULL, organization VARCHAR(255) NOT NULL, title VARCHAR(500) NOT NULL, url TEXT, section VARCHAR(500), accessed VARCHAR(32) NOT NULL, version VARCHAR(120), verification_status VARCHAR(40) NOT NULL DEFAULT 'partial', scope TEXT NOT NULL, content_hash VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS document_chunks (id BIGSERIAL PRIMARY KEY, source_id BIGINT NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE, chunk_key VARCHAR(180) NOT NULL, text TEXT NOT NULL, tags_json JSONB NOT NULL DEFAULT '[]'::jsonb, request_types_json JSONB NOT NULL DEFAULT '[]'::jsonb, services_json JSONB NOT NULL DEFAULT '[]'::jsonb, insurer_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb, verification_status VARCHAR(40) NOT NULL DEFAULT 'partial', content_hash VARCHAR(64) NOT NULL, CONSTRAINT uq_source_chunk UNIQUE(source_id, chunk_key));
CREATE TABLE IF NOT EXISTS claim_requests (id BIGSERIAL PRIMARY KEY, external_id VARCHAR(160) NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), contains_phi BOOLEAN NOT NULL DEFAULT FALSE, patient_name_enc TEXT, dob_enc TEXT, member_id_enc TEXT, mrn_enc TEXT, insurer_slug VARCHAR(120) NOT NULL, tpa_slug VARCHAR(120) NOT NULL, service_category VARCHAR(80) NOT NULL, request_type VARCHAR(40) NOT NULL, payload_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT uq_claim_owner_external UNIQUE(created_by, external_id));
CREATE TABLE IF NOT EXISTS assessments (id BIGSERIAL PRIMARY KEY, claim_request_id BIGINT NOT NULL REFERENCES claim_requests(id) ON DELETE CASCADE, engine_version VARCHAR(80) NOT NULL DEFAULT 'claimbot-v0.4', result_json JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS denials (id BIGSERIAL PRIMARY KEY, claim_request_id BIGINT REFERENCES claim_requests(id), denial_text_enc TEXT, classification VARCHAR(100) NOT NULL, analysis_json JSONB NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reconsideration_packages (id BIGSERIAL PRIMARY KEY, denial_id BIGINT NOT NULL REFERENCES denials(id), basis VARCHAR(40) NOT NULL, package_json JSONB NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS audit_events (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), action VARCHAR(120) NOT NULL, object_type VARCHAR(120) NOT NULL, object_id VARCHAR(160), request_id VARCHAR(160), metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_document_chunks_hash ON document_chunks(content_hash);
CREATE INDEX IF NOT EXISTS idx_claim_requests_created_by ON claim_requests(created_by);
CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON audit_events(created_at DESC);
